version: "3.8"

services:
  api:
    build: ./backend/api-gateway
    ports:
      - "3000:3000"
    env_file: .env
<<<<<<< HEAD
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/images
      REDIS_HOST: redis
      REDIS_PORT: 6379
=======
>>>>>>> 06d37f68f9d67736815b83a234c72d1cd96eb3e9
    depends_on:
      - postgres
      - redis

  worker:
    build: ./backend/worker
    env_file: .env
<<<<<<< HEAD
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/images
      REDIS_HOST: redis
      REDIS_PORT: 6379
=======
>>>>>>> 06d37f68f9d67736815b83a234c72d1cd96eb3e9
    depends_on:
      - redis
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "5173:80"

  postgres:
<<<<<<< HEAD
    image: postgres:15-alpine
=======
    image: postgres
>>>>>>> 06d37f68f9d67736815b83a234c72d1cd96eb3e9
    environment:
      POSTGRES_DB: images
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
<<<<<<< HEAD
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
=======

  redis:
    image: redis
>>>>>>> 06d37f68f9d67736815b83a234c72d1cd96eb3e9
